version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: RAG application service
  # Uncomment to run the Streamlit app in Docker
  # rag-app:
  #   build: .
  #   container_name: rag_app
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - QDRANT_URL=http://qdrant:6333
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   depends_on:
  #     qdrant:
  #       condition: service_healthy
  #   volumes:
  #     - ./data:/app/data
  #     - ./examples:/app/examples
  #   command: streamlit run examples/streamlit_app.py --server.address 0.0.0.0

volumes:
  qdrant_data:
    driver: local