server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-assistant-backend
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  h2:
    console:
      enabled: true
      path: /h2-console

# CORS configuration
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  
# LangChain service configuration
langchain:
  service:
    url: "http://localhost:8000"
    timeout: 30000

logging:
  level:
    com.aiassistant: DEBUG
    org.springframework.web: DEBUG